# Generated by Django 3.2 on 2024-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenic_id', models.IntegerField(choices=[(1, '西湖'), (2, '西溪湿地'), (3, '千岛湖'), (4, '良渚古城'), (5, '大明山')])),
                ('attraction_name', models.CharField(max_length=255, verbose_name='景点名称')),
                ('attraction_lng', models.FloatField()),
                ('attraction_lat', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(default=None, verbose_name='景点描述')),
                ('category', models.IntegerField(choices=[(1, '自然风光'), (2, '历史遗迹'), (3, '文化遗产'), (4, '娱乐体验')])),
                ('fee', models.FloatField(default=None)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('flow_limit', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, '未开放'), (1, '开放中'), (2, '人流预警')], default=0)),
                ('count', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('scenic_id', models.IntegerField(choices=[(1, '西湖'), (2, '西溪湿地'), (3, '千岛湖'), (4, '良渚古城'), (5, '大明山')], primary_key=True, serialize=False)),
                ('scenic_name', models.CharField(max_length=255)),
                ('scenic_lng', models.FloatField()),
                ('scenic_lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('description', models.CharField(max_length=200, verbose_name='景点描述')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
