# Generated by Django 3.2 on 2024-02-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='phone',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
