# Generated by Django 3.2 on 2024-02-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0002_attraction_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
