# Generated by Django 3.2 on 2025-04-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0002_add_missing_chat_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='scenic_id',
        ),
    ]
