# Generated by Django 3.2 on 2025-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0003_add_missing_scenic_fk'),
        ('scenic', '0003_remove_attraction_scenic_id'),
    ]

    operations = [
    ]
