# Generated by Django 3.2 on 2024-02-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0003_alter_attraction_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='fee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
