# Generated by Django 5.2 on 2025-04-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenic", "0004_merge_20250424_1335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="category",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Natural"),
                    (2, "Historical"),
                    (3, "Cultural"),
                    (4, "entertaining"),
                ],
                verbose_name="景点类别",
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Closed"), (1, "Opening"), (2, "Crowded")],
                default=0,
                verbose_name="景点状态",
            ),
        ),
    ]
