# Generated by Django 3.2 on 2024-02-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0004_auto_20240221_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='scenic_id',
        ),
        migrations.AddField(
            model_name='attraction',
            name='scenic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenic.scenic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '自然风光'), (2, '历史遗迹'), (3, '文化遗产'), (4, '娱乐体验')], verbose_name='景点类别'),
        ),
    ]
