# Generated by Django 5.2 on 2025-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenic", "0005_alter_attraction_category_alter_attraction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="category",
            field=models.SmallIntegerField(
                choices=[
                    (1, "自然风光"),
                    (2, "历史遗迹"),
                    (3, "文化遗产"),
                    (4, "娱乐体验"),
                ],
                verbose_name="景点类别",
            ),
        ),
    ]
