# Generated by Django 3.2 on 2024-02-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0005_auto_20240222_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开放'), (1, '开放中'), (2, '人流预警')], default=0),
        ),
    ]
