# Generated by Django 3.2 on 2024-02-23 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0006_alter_attraction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='address',
            field=models.CharField(max_length=255, verbose_name='景点地址'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='close_time',
            field=models.TimeField(verbose_name='关闭时间'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='fee',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='景点门票'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='flow_limit',
            field=models.IntegerField(verbose_name='人流量限制'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='open_time',
            field=models.TimeField(verbose_name='开放时间'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='景点电话'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='scenic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.scenic', verbose_name='所属景区'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开放'), (1, '开放中'), (2, '人流预警')], default=0, verbose_name='景点状态'),
        ),
    ]
