# Generated by Django 3.2 on 2024-02-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0007_auto_20240223_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attraction_lat',
            field=models.FloatField(verbose_name='景点纬度'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_lng',
            field=models.FloatField(verbose_name='景点经度'),
        ),
    ]
