# Generated by Django 5.2 on 2025-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenic", "0007_alter_attraction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Pending"), (1, "Paid"), (2, "Used"), (3, "Canceled")],
                default=0,
                verbose_name="购票订单状态",
            ),
        ),
    ]
