# Generated by Django 3.2 on 2024-02-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0008_auto_20240223_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=50, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
