# Generated by Django 3.2 on 2024-02-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0009_auto_20240224_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_route_name', models.CharField(max_length=100)),
                ('scenic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.scenic')),
            ],
        ),
        migrations.CreateModel(
            name='TourOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.attraction')),
                ('tour_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.tourroute')),
            ],
        ),
    ]
