# Generated by Django 3.2 on 2024-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0010_tourorder_tourroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourroute',
            name='tour_route_name',
        ),
        migrations.AddField(
            model_name='tourroute',
            name='route_description',
            field=models.TextField(blank=True, null=True, verbose_name='路线描述'),
        ),
        migrations.AddField(
            model_name='tourroute',
            name='route_name',
            field=models.CharField(default='春日赏花线', max_length=100, verbose_name='路线名称'),
            preserve_default=False,
        ),
    ]
