# Generated by Django 3.2 on 2024-02-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0011_auto_20240225_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_count', models.PositiveIntegerField(default=1, verbose_name='购票数量')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已完成'), (3, '已取消')], default=0, verbose_name='购票订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='购票订单创建时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.attraction', verbose_name='所购景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.user', verbose_name='购票用户')),
            ],
        ),
    ]
