# Generated by Django 3.2 on 2024-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0012_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attraction_images/', verbose_name='景点图片'),
        ),
    ]
