# Generated by Django 3.2 on 2024-03-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0013_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='count',
            field=models.IntegerField(default=0, verbose_name='景点实时人数'),
        ),
        migrations.CreateModel(
            name='RecommendationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('strategy_description', models.TextField(blank=True, null=True)),
                ('strategy_type', models.SmallIntegerField(choices=[(1, '按实时人数推荐'), (2, '按景点热度推荐'), (3, '自定义推荐列表'), (4, '组合策略'), (5, '个性化推荐')], verbose_name='推荐策略类型')),
                ('scenic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to='scenic.scenic', verbose_name='所属景区')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='推荐顺序')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.attraction', verbose_name='推荐景点')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.recommendationstrategy', verbose_name='所属推荐策略')),
            ],
        ),
    ]
