# Generated by Django 3.2 on 2024-03-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0014_auto_20240328_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationstrategy',
            name='status',
            field=models.BooleanField(default=False, verbose_name='策略状态'),
        ),
    ]
