# Generated by Django 3.2 on 2024-04-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0015_recommendationstrategy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scenic_images/', verbose_name='景区图片'),
        ),
    ]
