# Generated by Django 3.2 on 2024-04-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0016_scenic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenic',
            name='scale',
            field=models.IntegerField(default=14, verbose_name='地图尺寸'),
        ),
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('manual_check', models.BooleanField(default=False)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.attraction')),
                ('scenic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.scenic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.user')),
            ],
        ),
    ]
