# Generated by Django 3.2 on 2024-04-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0017_auto_20240407_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenic',
            name='scale',
        ),
    ]
