# Generated by Django 3.2 on 2024-04-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0018_remove_scenic_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenic',
            name='scale',
            field=models.IntegerField(blank=True, null=True, verbose_name='地图尺寸'),
        ),
    ]
