# Generated by Django 3.2 on 2024-04-07 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0019_scenic_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
