# Generated by Django 3.2 on 2024-04-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0020_alter_footprint_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateField(blank=True, null=True, verbose_name='游玩日期'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='游客姓名')),
                ('idcard', models.CharField(max_length=18, verbose_name='游客身份证号')),
                ('phone', models.CharField(max_length=15, verbose_name='游客手机号')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='scenic.ticket')),
            ],
        ),
    ]
