# Generated by Django 3.2 on 2024-05-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0021_auto_20240417_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.attraction')),
                ('scenic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.scenic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.user')),
            ],
        ),
    ]
