# Generated by Django 3.2 on 2024-05-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0022_stayrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourroute',
            name='status',
            field=models.BooleanField(default=False, verbose_name='路线状态'),
        ),
    ]
