# Generated by Django 3.2 on 2024-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0023_tourroute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='景点描述'),
        ),
    ]
